<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <CiExtraTargetFrameworksSuffix Condition="'$(EnableCiTargetFrameworks)' == 'true'">;net10.0;net9.0;net8.0</CiExtraTargetFrameworksSuffix>
    <TargetFrameworks>netstandard2.0;net472$(CiExtraTargetFrameworksSuffix)</TargetFrameworks>
    <AssemblyName>dotacp.$(MSBuildProjectName)</AssemblyName>
    <RootNamespace>dotacp.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
    <Nullable>enable</Nullable>
    <PackageId>dotacp.client</PackageId>
    <Title>.NET library for implementing Agent Client Protocol (ACP) clients (editors/IDEs).</Title>
    <Description>This package provides the tools needed to integrate Agent Client Protocol (ACP) agent support into editors, IDEs, and other client applications.</Description>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StreamJsonRpc" Version="2.7.76" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\protocol\protocol.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="README.md" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\shared\*.cs" />
  </ItemGroup>

</Project>
