<Project>
  <PropertyGroup>
    <LangVersion>8.0</LangVersion>

    <PackageVersion>0.1.0</PackageVersion>
    <Version>$(PackageVersion)</Version>
    <VersionPrefix>$([System.String]::Copy('$(PackageVersion)').Split('-')[0])</VersionPrefix>

    <Description>Agent Client Protocol .NET SDK.</Description>
    <PackageTags>acp;agentclientprotocol;agent;client</PackageTags>
    <RepositoryUrl>https://github.com/timxx/dotacp</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>$(RepositoryUrl)</PackageProjectUrl>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Authors>timxx</Authors>
    <Copyright>© Weitian Leung</Copyright>

    <AssemblyVersion>$(VersionPrefix)</AssemblyVersion>
    <FileVersion>$(VersionPrefix)</FileVersion>

    <NuGetAuditLevel>critical</NuGetAuditLevel>
  </PropertyGroup>
</Project>
