<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <CiExtraTargetFrameworksSuffix Condition="'$(EnableCiTargetFrameworks)' == 'true'">;net10.0;net9.0;net8.0</CiExtraTargetFrameworksSuffix>
    <TargetFrameworks>netstandard2.0;net472$(CiExtraTargetFrameworksSuffix)</TargetFrameworks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="schema\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <PropertyGroup>
    <SchemaHashFile>$(ProjectDir)obj\$(Configuration)\schema.hash</SchemaHashFile>
    <AssemblyName>dotacp.$(MSBuildProjectName)</AssemblyName>
    <RootNamespace>dotacp.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
    <PackageId>dotacp.protocol</PackageId>
    <Title>Type-safe .NET protocol definitions for the Agent Client Protocol (ACP).</Title>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="README.md" />
  </ItemGroup>

</Project>
